import * as XLSX from 'xlsx'

export function getQuotationTemplateData() {
    return [
        {
            Grupo_Cotizacion: '1',
            Cliente_Documento: '12345678',
            Cliente_Nombre: 'Cliente Ejemplo S.A.S.',
            Sucursal_Codigo: 'BOG01',
            Implant_Codigo: 'IMP01',
            Vendedor_Codigo: 'VEN-001',
            Tiqueteador_Codigo: 'TIQ-001',
            Moneda: 'USD',
            Tasa_Cambio: 4000,
            Comision_Global_Pct: 10,
            Cargos_A_Cotizacion: 0,
            Producto_Codigo: 'AL-DES',
            Proveedor_Codigo: 'GHL',
            Prestadora_Codigo: 'GHL-BOG',
            Impuestos_Nombres_Y_Valores: 'IVA:95.50|FEE:10.00',
            Variables_Codigos_Y_Valores: 'TKT-VUELO:784561|PNR-RESERVA:XYZZ12',
            Pasajeros: 'Juan Perez:12345678|Maria Garcia:87654321',
            Precio_Unitario: 15.0,
            Cantidad: 2,
            Costo: 10.0,
            CheckIn: '2026-12-01',
            CheckOut: '2026-12-10',
            Pax_Adultos: 2,
            Pax_Ninos: 0,
            Destino: 'BOG',
            Tipo_Servicio: 'ALIMENTACION',
            Reserva: 'RES123',
            Comision_Vendedor_Producto: 0,
            Comision_Tiqueteador_Producto: 0,
            Combo_Codigos: '',
            Nacionalidad: 1,
            Cargo_Principal: 'IVA-19',
            Servicios: 'Desayuno Buffet Incluido',
            Descripcion: 'Alojamiento con Desayuno',
            Fecha_Vencimiento_Proveedor: '2026-11-25',
            Factura_Proveedor: 'FPROV-99881'
        },
        {
            Grupo_Cotizacion: '1',
            Cliente_Documento: '12345678',
            Cliente_Nombre: 'Cliente Ejemplo S.A.S.',
            Sucursal_Codigo: 'BOG01',
            Implant_Codigo: 'IMP01',
            Vendedor_Codigo: 'VEN-001',
            Tiqueteador_Codigo: 'TIQ-001',
            Moneda: 'USD',
            Tasa_Cambio: 4000,
            Comision_Global_Pct: 10,
            Cargos_A_Cotizacion: 0,
            Producto_Codigo: 'TR-AERO',
            Proveedor_Codigo: 'DEC',
            Prestadora_Codigo: 'DEC-BARU',
            Impuestos_Nombres_Y_Valores: '',
            Variables_Codigos_Y_Valores: '',
            Pasajeros: '',
            Precio_Unitario: 25.0,
            Cantidad: 1,
            Costo: 20.0,
            CheckIn: '2026-12-01',
            CheckOut: '2026-12-01',
            Pax_Adultos: 2,
            Pax_Ninos: 0,
            Destino: 'CTG',
            Tipo_Servicio: 'TRANSPORTE',
            Reserva: 'XXL123',
            Comision_Vendedor_Producto: 5,
            Comision_Tiqueteador_Producto: 2,
            Combo_Codigos: '',
            Nacionalidad: 1,
            Cargo_Principal: 'IVA-19',
            Servicios: 'Traslado Privado Aeropuerto-Hotel',
            Descripcion: 'Servicio de transfer',
            Fecha_Vencimiento_Proveedor: '',
            Factura_Proveedor: ''
        }
    ]
}

export function getInvoiceTemplateData() {
    return [
        {
            Grupo_Factura: '1',
            Cliente_Documento: '12345678',
            Cliente_Nombre: 'Cliente Ejemplo S.A.S.',
            Sucursal_Codigo: 'BOG01',
            Implant_Codigo: 'IMP01',
            Vendedor_Codigo: 'VEN-001',
            Tiqueteador_Codigo: 'TIQ-001',
            Moneda: 'USD',
            Tasa_Cambio: 4000,
            Comision_Global_Pct: 10,
            Cargos_A_Factura: 0,
            Producto_Codigo: 'AL-DES',
            Proveedor_Nombre: 'Hotel GHL',
            Proveedor_Codigo: 'GHL',
            Prestadora_Codigo: 'GHL-BOG',
            Impuestos_Nombres_Y_Valores: 'IVA-19:19000|FEE:5000',
            Variables_Codigos_Y_Valores: 'PNR-RESERVA:XYZZ12',
            Pasajeros: 'Juan Perez:12345678|Maria Garcia:87654321',
            Precio_Unitario: 100000.0,
            Cantidad: 2,
            CheckIn: '2026-12-01',
            CheckOut: '2026-12-10',
            Pax_Adultos: 2,
            Pax_Ninos: 0,
            Destino: 'BOG',
            Tipo_Servicio: 'ALIMENTACION',
            Reserva: 'RES123',
            Comision_Vendedor_Producto: 5.0,
            Comision_Tiqueteador_Producto: 2.0,
            Combo_Codigos: '',
            Nacionalidad: 1,
            Cargo_Principal: 'IVA-19',
            Costo: 80000.0,
            Servicios: 'Desayuno incluido',
            Descripcion: 'Habitación doble estándar',
            Itinerario: '',
            Clase: '',
            Aerolinea: '',
            Tipo_Tiquete_Codigo: '',
            Pagos: '100000:Efectivo:REF-123|100000:Tarjeta:REF-456:2026-12-01:1:1234:AUTH123:VOUCH456:2028-12',
            Itinerarios: '',
            Fuente: 'FAC',
            Serie: 'A',
            Consecutivo: '000123',
            Fecha_Vencimiento_Proveedor: '2026-11-25',
            Factura_Proveedor: 'FPROV-99881'
        },
        {
            Grupo_Factura: '2',
            Cliente_Documento: '87654321',
            Cliente_Nombre: 'Comercializadora Global Ltda.',
            Sucursal_Codigo: 'BOG01',
            Implant_Codigo: 'IMP01',
            Vendedor_Codigo: 'VEN-002',
            Tiqueteador_Codigo: 'TIQ-002',
            Moneda: 'COP',
            Tasa_Cambio: 1,
            Comision_Global_Pct: 0,
            Cargos_A_Factura: 15000,
            Producto_Codigo: 'TKT-AIR',
            Proveedor_Nombre: 'Avianca',
            Proveedor_Codigo: 'AV',
            Prestadora_Codigo: 'AV-BOG',
            Impuestos_Nombres_Y_Valores: 'IVA-19:57000',
            Variables_Codigos_Y_Valores: 'TKT-N:000123456',
            Pasajeros: 'Carlos Gomez:10987654',
            Precio_Unitario: 300000.0,
            Cantidad: 1,
            CheckIn: '2026-10-15',
            CheckOut: '2026-10-15',
            Pax_Adultos: 1,
            Pax_Ninos: 0,
            Destino: 'CTG',
            Tipo_Servicio: 'Tiquete',
            Reserva: 'AVPNR7',
            Comision_Vendedor_Producto: 0,
            Comision_Tiqueteador_Producto: 0,
            Combo_Codigos: '',
            Nacionalidad: 1,
            Cargo_Principal: 'IVA-19',
            Costo: 250000.0,
            Servicios: 'Equipaje de mano',
            Descripcion: 'Vuelo directo de ida',
            Itinerario: 'BOG-CTG',
            Clase: 'Económica',
            Aerolinea: 'Avianca',
            Tipo_Tiquete_Codigo: 'TKT-NAC',
            Pagos: '357000:Efectivo:REF-789',
            Itinerarios: 'BOG:CTG:Económica:2026-10-15:2026-10-15:1|CTG:BOG:Económica:2026-10-20:2026-10-20:2',
            Fuente: 'FAC',
            Serie: 'A',
            Consecutivo: '000124',
            Fecha_Vencimiento_Proveedor: '2026-10-10',
            Factura_Proveedor: 'AV-98124'
        }
    ]
}

export function downloadQuotationTemplate() {
    const templateData = getQuotationTemplateData()
    const ws = XLSX.utils.json_to_sheet(templateData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Plantilla Cotizaciones')
    XLSX.writeFile(wb, 'plantilla_cotizacion.xlsx')
}

export function downloadInvoiceTemplate() {
    const templateData = getInvoiceTemplateData()
    const ws = XLSX.utils.json_to_sheet(templateData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Plantilla Facturas')
    XLSX.writeFile(wb, 'plantilla_factura.xlsx')
}
